#!/bin/bash

#Initialize variables to null string
workingDir=""

#Get current directory so we can reset it when we're done
currentDir="$(pwd)"

#Hint to user to use build -h for help
helpHint="Use \"mongodb_test -h\" for valid options and usage help"

#Parse Options
while getopts ":hd:" option; do
	case ${option} in
		h )
			#TODO help
			echo "TODO: help"
			exit 0
			;;
		d )
			if [ ! -d "$OPTARG" ]
			then
				echo "Invalid argument for option -d: $OPTARG is not a directory" 1>&2
				echo "$helpHint"
				exit 73
			elif [ ! -r "$OPTARG" ]
			then
				echo "Permission Denied: Cannot read from $OPTARG" 1>&2
				echo "$helpHint"
				exit 77
			elif [ ! -w "$OPTARG" ]
			then
				echo "Permission Denied: Cannot write to $OPTARG" 1>&2
				echo "$helpHint"
				exit 77
			else
				workingDir=$OPTARG
			fi
			;;
		#Catch invalid options
		\? )
			echo "Invalid option: $OPTARG" 1>&2
			echo "$helpHint"
			exit 64
			;;
		#Catch missing agruments
		: )
			echo "Missing required argument for option: $OPTARG" 1>&2
			echo "$helpHint"
			exit 64
			;;
	esac
done
shift $((OPTIND -1))

#Set defaults for options if not specified
if [ -z $workingDir ]
then
	workingDir="$(pwd)/mongodb"
fi

. /etc/os-release

set -x

container=$(buildah from scratch)
containerMount=$(buildah mount $container)

dnf install --installroot ${containerMount} bash coreutils python2.7 gcc gcc-c++ --releasever ${VERSION_ID} --setopt=install_weak_deps=false --setopt=tsflags=nodocs -y
dnf clean all -y --installroot ${containerMount} --releasever ${VERSION_ID}
cp -r ${workingDir} ${containerMount}/mongodb

buildah config --workingdir='/mongodb' $container

#install python requirements
buildah run ${container} -- python2.7 -m ensurepip
buildah run ${container} -- python2.7 -m pip install -r buildscripts/resmokelib/requirements.txt

buildah run ${container} -- python2.7 buildscripts/resmoke.py --suites=core,ssl
