language: cpp
os: linux
dist: focal
env:
  global:
    - MONGODB_VERSION=3.6
stages:
  - Create Workspaces
jobs:
  include:
    - stage: Create Workspaces
      name: arm64
      arch: arm64
      workspaces:
        create:
          - name: mongodb-arm64
            paths: 
              - $HOME/mongodb-arm64
          - name: mongodb-amd64
            paths:
              - $HOME/mongodb-amd64
      git:
        clone: false
      install: skip
      script:
        - export MONGO_RELEASE=$(git ls-remote --tags --sort="-v:refname" https://github.com/mongodb/mongo.git "r$MONGODB_VERSION*" | grep -o -m 1 "r[0-9\.]*$")
        - git clone --depth=1 --branch="$MONGO_RELEASE" https://github.com/mongodb/mongo.git $HOME/mongodb-arm64
        - git clone --depth=1 --branch="$MONGO_RELEASE" https://github.com/mongodb/mongo.git $HOME/mongodb-amd64
