language: cpp
os: linux
dist: focal
env:
  global:
    - MONGODB_VERSION=3.6
    - BUILD_FROM_DIST="centos"
cache: 
  - pip
  - ccache

stages:
  - Compile Mongo
  - Finish Compiling Mongo
  - Compile Mongod
  - Finish Compiling Mongod
  - Test MongoDB

jobs:
  include:
    - stage: Compile Mongo
      name: Compile Mongo arm64
      arch: arm64-graviton2
      virt: vm
      group: edge
      workspaces:
        create:
          - name: mongo-partial-arm64
            paths: 
              - ${HOME}/mongodb
      install: ${TRAVIS_BUILD_DIR}/ci/install_mongodb
      script:
        - mkdir -p ${HOME}/mongodb
        - rm -f ${HOME}/mongodb/not_finished
        - timeout --kill-after=30s 35m ${TRAVIS_BUILD_DIR}/build_mongodb -a aarch64 -j 4 -d ${HOME}/mongodb mongo; build_exit=$?; if [ $build_exit -eq 124 ] || [ $build_exit -eq 137 ]; then echo "Build taking a while. Will resume in next stage."; touch ${HOME}/mongodb/not_finished; else return $build_exit; fi
    
    - stage: Compile Mongo
      name: Compile Mongo amd64
      arch: amd64
      workspaces:
        create:
          - name: mongo-partial-amd64
            paths: 
              - ${HOME}/mongodb
      install: ${TRAVIS_BUILD_DIR}/ci/install_mongodb
      script:
        - mkdir -p ${HOME}/mongodb
        - rm -f ${HOME}/mongodb/not_finished
        - timeout --kill-after=30s 35m ${TRAVIS_BUILD_DIR}/build_mongodb -a x86_64 -j 4 -d ${HOME}/mongodb mongo; build_exit=$?; if [ $build_exit -eq 124 ] || [ $build_exit -eq 137 ]; then echo "Build taking a while. Will resume in next stage."; touch ${HOME}/mongodb/not_finished; else return $build_exit; fi

    - stage: Finish Compiling Mongo
      name: Finish Compiling Mongo arm64
      arch: arm64-graviton2
      virt: vm
      group: edge
      workspaces:
        use: mongo-partial-arm64
        create:
          - name: mongo-arm64
            paths: 
              - ${HOME}/mongodb
      install: ${TRAVIS_BUILD_DIR}/ci/install_mongodb
      script:
        - if [ -f ${HOME}/mongodb/not_finished ]; then echo "Resuming Build."; rm -f ${HOME}/mongodb/not_finished; ${TRAVIS_BUILD_DIR}/build_mongodb -a aarch64 -j 4 -d ${HOME}/mongodb -n mongo; else echo "Build already completed."; fi
        
    - stage: Finish Compiling Mongo
      name: Finish Compiling Mongo amd64
      arch: amd64
      workspaces:
        use: mongo-partial-amd64
        create:
          - name: mongo-amd64
            paths: 
              - ${HOME}/mongodb
      install: ${TRAVIS_BUILD_DIR}/ci/install_mongodb
      script:
        - if [ -f ${HOME}/mongodb/not_finished ]; then echo "Resuming Build."; rm -f ${HOME}/mongodb/not_finished; ${TRAVIS_BUILD_DIR}/build_mongodb -a x86_64 -j 4 -d ${HOME}/mongodb -n mongo; else echo "Build already completed."; fi

    - stage: Compile Mongod
      name: Compile Mongod arm64
      arch: arm64-graviton2
      virt: vm
      group: edge
      workspaces:
        use: mongo-arm64
        create:
          - name: mongod-partial-arm64
            paths: 
              - ${HOME}/mongodb
      install: ${TRAVIS_BUILD_DIR}/ci/install_mongodb
      script:
        - rm -f ${HOME}/mongodb/not_finished
        - timeout --kill-after=30s 35m ${TRAVIS_BUILD_DIR}/build_mongodb -a aarch64 -j 4 -d ${HOME}/mongodb -n mongod; build_exit=$?; if [ $build_exit -eq 124 ] || [ $build_exit -eq 137 ]; then echo "Build taking a while. Will resume in next stage."; touch ${HOME}/mongodb/not_finished; else return $build_exit; fi
        
    - stage: Compile Mongod
      name: Compile Mongod amd64
      arch: amd64
      workspaces:
        use: mongo-amd64
        create:
          - name: mongod-partial-amd64
            paths: 
              - ${HOME}/mongodb
      install: ${TRAVIS_BUILD_DIR}/ci/install_mongodb
      script:
        - rm -f ${HOME}/mongodb/not_finished
        - timeout --kill-after=30s 35m ${TRAVIS_BUILD_DIR}/build_mongodb -a x86_64 -j 4 -d ${HOME}/mongodb -n mongod; build_exit=$?; if [ $build_exit -eq 124 ] || [ $build_exit -eq 137 ]; then echo "Build taking a while. Will resume in next stage."; touch ${HOME}/mongodb/not_finished; else return $build_exit; fi

    - stage: Finish Compiling Mongod
      name: Finish Compiling Mongod arm64
      arch: arm64-graviton2
      virt: vm
      group: edge
      workspaces:
        use: mongod-partial-arm64
        create:
          - name: mongod-arm64
            paths: 
              - ${HOME}/mongodb
      install: ${TRAVIS_BUILD_DIR}/ci/install_mongodb
      script:
        - if [ -f ${HOME}/mongodb/not_finished ]; then echo "Resuming Build."; rm -f ${HOME}/mongodb/not_finished; ${TRAVIS_BUILD_DIR}/build_mongodb -a aarch64 -j 4 -d ${HOME}/mongodb -n mongod; else echo "Build already completed."; fi
        
    - stage: Finish Compiling Mongod
      name: Finish Compiling Mongod amd64
      arch: amd64
      workspaces:
        use: mongod-partial-amd64
        create:
          - name: mongod-amd64
            paths: 
              - ${HOME}/mongodb
      install: ${TRAVIS_BUILD_DIR}/ci/install_mongodb
      script:
        - if [ -f ${HOME}/mongodb/not_finished ]; then echo "Resuming Build."; rm -f ${HOME}/mongodb/not_finished; ${TRAVIS_BUILD_DIR}/build_mongodb -a x86_64 -j 4 -d ${HOME}/mongodb -n mongod; else echo "Build already completed."; fi

    - stage: Test MongoDB
      name: Run MongoDB Tests in arm64 container
      arch: arm64-graviton2
      virt: vm
      group: edge
      workspaces:
        use: mongod-arm64
      install: ${TRAVIS_BUILD_DIR}/ci/install_tests
      script:
        - podman pull ${BUILD_FROM_DIST}:latest
        - podman run --rm=true -e BUILDAH_ISOLATION=chroot -v ${TRAVIS_BUILD_DIR}:/build:rw -v ${HOME}/mongodb:/mongodb:rw ${BUILD_FROM_DIST}:latest /bin/bash -c "dnf update --refresh -y && dnf install -y podman buildah && buildah unshare bash -c '/build/ci/test_mongodb -d /mongodb'"

    - stage: Test MongoDB
      name: Run MongoDB Tests in amd64 container
      arch: amd64
      workspaces:
        use: mongod-amd64
      install: ${TRAVIS_BUILD_DIR}/ci/install_tests
      script:
        - podman pull ${BUILD_FROM_DIST}:latest
        - podman run --rm=true -e BUILDAH_ISOLATION=chroot -v ${TRAVIS_BUILD_DIR}:/build:rw -v ${HOME}/mongodb:/mongodb:rw ${BUILD_FROM_DIST}:latest /bin/bash -c "dnf update --refresh -y && dnf install -y podman buildah && buildah unshare bash -c '/build/ci/test_mongodb -d /mongodb'"
