language: cpp
os: linux
dist: focal
env:
  global:
    - MONGODB_VERSION=3.6
cache: 
  - pip
  - ccache

stages:
  - Create Workspaces
  - Compile Mongo
  - Compile Mongod
  - Finish Compiling Mongod

install:
  - sudo apt update
  - sudo apt install build-essential python2.7 libpython2.7-dev libboost-filesystem-dev libboost-program-options-dev libboost-system-dev libboost-thread-dev
  - export CURDIR=$(pwd)
  - cd $HOME
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - python2.7 get-pip.py
  - rm -f get-pip.py
  - cd $CURDIR
  - unset CURDIR
  - python2.7 -m pip install -r $HOME/mongodb/buildscripts/requirements.txt

jobs:
  include:
    - stage: Create Workspaces
      name: Create arm64 Workspace
      arch: arm64
      workspaces:
        create:
          - name: mongodb-arm64
            paths: 
              - $HOME/mongodb
      git:
        clone: false
      install: skip
      script:
        - export MONGO_RELEASE=$(git ls-remote --tags --sort="-v:refname" https://github.com/mongodb/mongo.git "r$MONGODB_VERSION*" | grep -o -m 1 "r[0-9\.]*$")
        - git clone --depth=1 --branch="$MONGO_RELEASE" https://github.com/mongodb/mongo.git $HOME/mongodb

    - stage: Create Workspaces
      name: Create amd64 Workspace
      arch: amd64
      workspaces:
        create:
          - name: mongodb-amd64
            paths:
              - $HOME/mongodb
      git:
        clone: false
      install: skip
      script:
        - export MONGO_RELEASE=$(git ls-remote --tags --sort="-v:refname" https://github.com/mongodb/mongo.git "r$MONGODB_VERSION*" | grep -o -m 1 "r[0-9\.]*$")
        - git clone --depth=1 --branch="$MONGO_RELEASE" https://github.com/mongodb/mongo.git $HOME/mongodb

    - stage: Compile Mongo
      name: Compile Mongo arm64
      arch: arm64
      git:
        clone: false
      workspaces:
        use: mongodb-arm64
      script:
        - cd $HOME/mongodb
        - python2.7 buildscripts/scons.py -j4 mongo --disable-warnings-as-errors CC=/usr/lib/ccache/gcc CXX=/usr/lib/ccache/g++ CCFLAGS="-march=armv8-a+crc -w"
        
    - stage: Compile Mongo
      name: Compile Mongo amd64
      arch: amd64
      git:
        clone: false
      workspaces:
        use: mongodb-amd64
      script:
        - cd $HOME/mongodb
        - python2.7 buildscripts/scons.py -j4 mongo --disable-warnings-as-errors CC=/usr/lib/ccache/gcc CXX=/usr/lib/ccache/g++ CCFLAGS="-w"

    - stage: Compile Mongod
      name: Compile Mongod arm64
      arch: arm64
      git:
        clone: false
      workspaces:
        use: mongodb-arm64
      script:
        - cd $HOME/mongodb
        - timeout --kill-after=30s 40m python2.7 buildscripts/scons.py -j4 mongod --disable-warnings-as-errors CC=/usr/lib/ccache/gcc CXX=/usr/lib/ccache/g++ CCFLAGS="-march=armv8-a+crc -w"; build_exit=$?; if [ $build_exit -eq 124 ] || [ $build_exit -eq 137 ]; then echo "Build taking a while. Will resume in next stage."; touch $HOME/mongodb/not_finished; else return $build_exit; fi
        
    - stage: Compile Mongod
      name: Compile Mongod amd64
      arch: amd64
      git:
        clone: false
      workspaces:
        use: mongodb-amd64
      script:
        - cd $HOME/mongodb
        - timeout --kill-after=30s 40m python2.7 buildscripts/scons.py -j4 mongod --disable-warnings-as-errors CC=/usr/lib/ccache/gcc CXX=/usr/lib/ccache/g++ CCFLAGS="-w"; build_exit=$?; if [ $build_exit -eq 124 ] || [ $build_exit -eq 137 ]; then echo "Build taking a while. Will resume in next stage."; touch $HOME/mongodb/not_finished; else return $build_exit; fi

    - stage: Finish Compiling Mongod
      name: Finish Compiling Mongod arm64
      arch: arm64
      git:
        clone: false
      workspaces:
        use: mongodb-arm64
      script:
        - cd $HOME/mongodb
        - ls -al $HOME/mongodb/not_finished
        - if [ -f $HOME/mongodb/not_finished ]; then echo "Resuming Build."; rm -f $HOME/mongodb/not_finished; python2.7 buildscripts/scons.py -j4 mongod --disable-warnings-as-errors CC=/usr/lib/ccache/gcc CXX=/usr/lib/ccache/g++ CCFLAGS="-march=armv8-a+crc -w"; else echo "Build already completed!"; fi
        
    - stage: Finish Compiling Mongod
      name: Finish Compiling Mongod amd64
      arch: amd64
      git:
        clone: false
      workspaces:
        use: mongodb-amd64
      script:
        - cd $HOME/mongodb
        - ls -al $HOME/mongodb/not_finished
        - if [ -f $HOME/mongodb/not_finished ]; then echo "Resuming Build."; rm -f $HOME/mongodb/not_finished; python2.7 buildscripts/scons.py -j4 mongod --disable-warnings-as-errors CC=/usr/lib/ccache/gcc CXX=/usr/lib/ccache/g++ CCFLAGS="-w"; else echo "Build already completed!"; fi
