language: cpp
os: linux
dist: focal

jobs:
  include:
    - arch: arm64-graviton2
      virt: vm
      group: edge
      before_install:
        - . /etc/os-release
        - uname -m
      install:
        - echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
        - curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add -
        - sudo apt-get update
        - sudo apt-get -y install uidmap podman slirp4netns
      script:
        - podman pull centos:8
        - podman run --log-level debug --rm=true -e CENTOS_VERSION=8 -e BUILDAH_ISOLATION=chroot -v $TRAVIS_BUILD_DIR:/build:rw centos:8 /bin/bash -c "dnf update --refresh"
    - arch: amd64
      virt: vm
      before_install:
        - . /etc/os-release
      install:
        - echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
        - curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add -
        - sudo apt-get update 
        - sudo apt-get -y install uidmap podman slirp4netns
      script:
        - podman pull centos:8
        - podman run --log-level debug --rm=true -e CENTOS_VERSION=8 -e BUILDAH_ISOLATION=chroot -v $TRAVIS_BUILD_DIR:/build:rw centos:8 /bin/bash -c "dnf update --refresh"
