# This is a basic workflow to help you get started with Actions

name: Build

env:
  MONGODB_VERSION: 3.6

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: test
        run: |
          MONGO_RELEASE=$(git ls-remote --tags --sort="-v:refname" https://github.com/mongodb/mongo.git "r3.6*" | grep -o -m 1 "r[0-9\.]*$")
          git clone --depth=1 --branch="${MONGO_RELEASE}" https://github.com/mongodb/mongo.git ${HOME}/mongodb
          cd ${HOME}/mongodb
          python2.7 buildscripts/scons.py --help
