name: Build

env:
  MONGODB_VERSION: 3.6
  BUILD_FROM_DIST: fedora

on:
  push:
    branches:
      - main
      - testing
  pull_request:
    branches:
      - main
      - testing
  workflow_dispatch:

jobs:
  build_x86_64:
    name: Build for x86_64
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - uses: actions/checkout@v2

      - name: Install Build Deps
        run: ${GITHUB_WORKSPACE}/.github/scripts/mongodb_build_deps

      - name: Build MongoDB
        id: buildMongo
        if: success()
        run: |
          mkdir -p ${HOME}/mongodb
          #${GITHUB_WORKSPACE}/build_mongodb -a x86_64 -j 4 -d ${HOME} mongo mongod
          ${GITHUB_WORKSPACE}/build_mongodb -a x86_64 -j 4 -d ${HOME} mongod
          . ${HOME}/mongodb/mongoRelease
          echo "::set-output name=MONGODB_ARTIFACT_NAME::mongodb_x86_64_${MONGODB_RELEASE}"

      - name: Test MongoDB
        if: success()
        run: |
          ${GITHUB_WORKSPACE}/.github/scripts/mongodb_test_setup
          podman pull ${BUILD_FROM_DIST}:latest
          podman run --rm=true -e BUILDAH_ISOLATION=chroot -v ${GITHUB_WORKSPACE}:/build:rw -v ${HOME}/mongodb:/mongodb:rw ${BUILD_FROM_DIST}:latest /bin/bash -c "dnf update --refresh -y && dnf install -y podman buildah && buildah unshare bash -c '/build/.github/scripts/mongodb_test -d /mongodb'"
          
      - name: Archive MongoDB
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.buildMongo.outputs.MONGODB_ARTIFACT_NAME }}
          path: |
            ~/mongodb/build/opt/mongo/mongod

#  build_aarch64:
#    name: Build for aarch64
#    runs-on: ubuntu-latest
#    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"

#    steps:
#      - uses: actions/checkout@v2
#      - uses: uraimo/run-on-arch-action@v2.0.7

#        name: Build for aarch64
#        with:
#          arch: aarch64
#          distro: fedora_latest
#          setup: mkdir -p ${HOME}/mongodb
#          dockerRunArgs: -v ${HOME}/mongodb:/mongodb:rw -v ${GITHUB_WORKSPACE}:/github:rw
#          run: |
#            /github/.github/scripts/mongodb_build_deps
#            /github/build_mongodb -a x86_64 -j 4 -d /mongodb mongo mongod
