name: Build

env:
  MONGODB_VERSION: 3.6

on:
  push:
    branches:
      - main
      - testing
  pull_request:
    branches:
      - main
      - testing
  workflow_dispatch:

jobs:
  build_x86_64:
    name: Build for x86_64
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Build Deps
        run: ${GITHUB_WORKSPACE}/.github/scripts/mongodb_build_deps

      - name: Build MongoDB
        run: |
          mkdir -p ${HOME}/mongodb
          ${GITHUB_WORKSPACE}/build_mongodb -a x86_64 -j 4 -d ${HOME}/mongodb mongo mongod

  build_aarch64:
    name: Build for aarch64
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v2.0.7

        name: Build for aarch64
        with:
          arch: aarch64
          distro: fedora_latest
          setup: mkdir -p ${HOME}/mongodb
          dockerRunArgs: -v ${HOME}/mongodb:/mongodb:rw -v ${GITHUB_WORKSPACE}:/github:rw
          run: |
            /github/.github/scripts/mongodb_build_deps
            /github/build_mongodb -a x86_64 -j 4 -d /mongodb mongo mongod
